"""init

Revision ID: 4e47b856a842
Revises: 
Create Date: 2024-12-09 10:12:39.241164

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mssql

# revision identifiers, used by Alembic.
revision: str = '4e47b856a842'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('gds_reports',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('pnr_id', sa.CHAR(length=26), nullable=False),
    sa.Column('gds', sa.Enum('AMADEUS', 'AMEX', 'CWT', 'EGENCIA', 'LOBERG', 'SABRE', name='gds'), nullable=True),
    sa.Column('receiver', sa.Enum('ERV', 'GEOS', 'HENNER', 'HDI', 'PSA', 'SENTINEL', 'SOS', 'YLE', name='receiver'), nullable=True),
    sa.Column('pnr_file', sa.String(length=64), nullable=False),
    sa.Column('pnr', sa.String(length=16), nullable=True),
    sa.Column('pcc', sa.String(length=16), nullable=True),
    sa.Column('extra_info', mssql.JSON(), nullable=True),
    sa.Column('pnr_emails', mssql.JSON(), nullable=True),
    sa.Column('pnr_passengers', mssql.JSON(), nullable=True),
    sa.Column('received_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('converted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('routed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_gds_reports'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('gds_reports')
    # ### end Alembic commands ###
